apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-6bbv
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-6bbv
    app.kubernetes.io/part-of: tkwch-fix-0075-0051-app
  name: devfile-sample-6bbv
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-6bbv
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-6bbv
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkwch-fix-0075-0-15-tenant/tkwch-fix-0075-0051-app/devfile-sample-6bbv@sha256:1d8dee399b1d287f0f44f34f64b00cb4138d0993703471b61ebcdeda7687a970
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
